name: android-ndk-r22 Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - "**/android-ndk-r22/*"
      - "**/android-ndk-r22.yml"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          context: images/android-ndk-r22/
          file: images/android-ndk-r22/Dockerfile
          tags: kunitoki/android-ndk-r22:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
