name: clang-5 Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - "**/clang-5/*"
      - "**/clang-5.yml"
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: images/clang-5/
          file: images/clang-5/Dockerfile
          tags: kunitoki/clang-5:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
