name: gcc-9 Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - "**/gcc-9/*"
      - "**/gcc-9.yml"
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: images/gcc-9/
          file: images/gcc-9/Dockerfile
          tags: kunitoki/gcc-9:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
